Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "db01"
#   config.vm.network "private_network", ip: "192.168.56.23"
  config.vm.network "forwarded_port", guest: 5432, host: 5433


  config.vm.provider "vmware_desktop" do |vmware|
    vmware.memory = "2048"
    vmware.cpus = 2
    vmware.gui = false
    vmware.allowlist_verified = true
  end
  config.vm.provision "shell", path: "postgres.sh"
end